# Introducción a las ciencias de la computación *y programación en Python*

*Banco de Guatemala*  
*PES 2025-2026*  
*Programación I*  
*Septiembre de 2025*  

## Abstract

> "*I do not fear computers. I fear lack of them.*" **Isaac Asimov**

- Paquete de computación científica NumPy

    - Introducción
    
    - Conceptos básicos de utilización
    
    - Ejercicios

# NumPy

- Paquete de Python para **computación científica** de **alto desempeño** sobre vectores, matrices y estructuras de mayores dimensiones (tensores).

- Implementado en C y Fortran, por lo que cuando se **vectorizan** las oepraciones, el desempeño es muy bueno.

- Ofrece una estructura de datos `ndarray` para procesar de forma **eficiente** datos homogéneos.

- Capacidades de algebra lineal, transformada de Fourier y generación de números aleatorios.

## Pero, ¿y las listas de Python?

- Las listas son muy generales, pueden contener cualquier tipo de objeto.

    - Implementan tipos dinámicos.
    
    - No permiten operaciones matemáticas como la *multiplicación matricial* o *producto punto*.
    
- Los vectores de NumPy son de tipado estático y homogéneo. El tipo del arreglo se determina cuando se crea el vector.

    - Son eficientes en memoria.
    
    - Es posible implementar **funciones universales** (ufuncs).
    
    - El tipado estático permite implementar operaciones matemáticas de forma eficiente a través de C y Fortran.
    

### Comparación entre lenguajes de programación

![julia-benchmarks.svg](https://github.com/PES-BG-2025/notebooks/blob/main/figs/numpy/julia-benchmarks.svg?raw=1)

[5 Razones para aprender NumPy](https://insights.dice.com/2016/09/01/5-reasons-know-numpy/):

    It's fast
    It works very well with SciPy and other Libraries
    It lets you do matrix arithmetic
    It has lots of built-in functions
    It has universal functions


## Importando NumPy

In [13]:
import numpy as np

- Revisamos la versión de NumPy (importante al ver la documentación)

In [14]:
np.__version__


'2.0.2'

In [12]:
#numpy ver la version, sin usar alias
numpy.__version__
# no salga si ya es un alias

'2.0.2'

### Obteniendo ayuda

In [15]:
# Obtiene una ventana de ayuda
np.ndarray?

In [17]:
# Función help para una función
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

***
## La clase `ndarray`

- La clase básica de NumPy se llama `ndarray` (alias `array`). Sus atributos más importantes son:

    - `ndarray.ndim` : número de dimensiones del arreglo.

    - `ndarray.shape` : dimensiones del arreglo. Esta es una **tupla de enteros** que indica el tamaño de la matriz en cada dimensión. Para una matriz con $n$ filas y $m$ columnas, la forma será $(n, m)$. La longitud de la tupla de forma es, por lo tanto, el número de ejes, `ndim`.

    - `darray.size` : el número total de elementos del arreglo. Es igual al producto de los elementos de la tupla `shape`.

    - `ndarray.dtype` : un **objeto** que describe el **tipo** de los elementos en el arreglo. Es posible crear y especificar `dtypes` propios.
        - Adicionalmente, NumPy provee algunos tipos propios muy utilizados: `numpy.int32`, `numpy.int16`, and `numpy.float64`.

    - `ndarray.itemsize` : el tamaño en bytes de cada elemento en el arreglo. Por ejemplo, un arreglo de tipo `float64` tiene tamaño en bytes de $8 (=64/8)$. Equivalente a `ndarray.dtype.itemsize`.

    - `ndarray.data` : el búfer que contiene los elementos del arreglo. Aunque normalmente, no accedemos al atributo directamente, ya que hacemos uso de los elementos con *slicing*.



In [20]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
a.shape #La dimension del arreglo

(3, 5)

In [23]:
a.ndim #numero de dimension del arreglo

2

In [25]:
a.dtype # de que tipo de arreglo es
type(a.dtype)

numpy.dtypes.Int64DType

In [26]:
a = np.arange(15, dtype=np.float64).reshape(3, 5)
a.dtype.name

'float64'

In [27]:
a.dtype.name

'float64'

In [28]:
a.itemsize #cuantos bits es, como es 64 para nuestro caso, da 8 bit

8

In [30]:
a.data

In [ ]:
a.size

In [33]:
type(a)

numpy.ndarray

***
# Creando arreglos N-dimensionales de NumPy

- Hay varias formas de inicializar nuevas matrices numpy, por ejemplo desde

    - Una lista de Python o tuplas.
    
    - Utilizando funciones dedicadas a **generar** arreglos de NumPy.

      - Es común inicializar vectores de ceros o con valores aleatorios.
    
    - Leer información de archivos.

In [34]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [35]:
a.dtype

dtype('int64')

In [36]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [37]:
b.dtype

dtype('float64')

### Error frecuente

Crear el arreglo con varios argumentos en vez de proveer una sola lista o secuencia como argumento

In [40]:
# Error frecuente
a = np.array([1,2,3,4], dtype="int64")

## A partir de listas o tuplas
`ndarray` transforma secuencias de secuencias en matrices bidimensionales, secuencias de secuencias de secuencias en matrices tridimensionales, etc.

In [41]:
b = np.array([[1.5,2,3], [4,5,6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [44]:

#una matriz que tenga dimension atras de otra lista, usar lista de listas de listas
b = np.array([[[1.5,2,3], [4,5,6]],[[1.5,2,3], [4,5,7]]])
b

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[1.5, 2. , 3. ],
        [4. , 5. , 7. ]]])

In [47]:
#una matriz que tenga dimension atras de otra lista, usar lista de listas de listas, 4 dimensiones
b = np.array([[[[1.5,2,3], [4,5,6]],[[1.5,2,3], [4,5,7]]],[[[1.5,2,3], [4,5,6]],[[1.5,2,3], [4,5,8]]]])
b

array([[[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],

        [[1.5, 2. , 3. ],
         [4. , 5. , 7. ]]],


       [[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],

        [[1.5, 2. , 3. ],
         [4. , 5. , 8. ]]]])

El tipo de matriz también se puede especificar explícitamente en el momento de la creación:

In [48]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

## Funciones de generación de arreglos

In [51]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [53]:
# A diferencia de range
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [57]:
np.ones((2,3,2)) #arreglos de 1 con dimensiones columnaxfila, dimension

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

#### Evaluación de funciones

Notar que la evaluación de funciones es "vectorizada", es decir, sobre todos los elementos del arreglo a la vez.

- ¡Evitamos los ciclos `for` de Python porque son más lentos!

In [67]:
x = np.linspace(0, 2*np.pi, 50)
x

array([0.        , 0.12822827, 0.25645654, 0.38468481, 0.51291309,
       0.64114136, 0.76936963, 0.8975979 , 1.02582617, 1.15405444,
       1.28228272, 1.41051099, 1.53873926, 1.66696753, 1.7951958 ,
       1.92342407, 2.05165235, 2.17988062, 2.30810889, 2.43633716,
       2.56456543, 2.6927937 , 2.82102197, 2.94925025, 3.07747852,
       3.20570679, 3.33393506, 3.46216333, 3.5903916 , 3.71861988,
       3.84684815, 3.97507642, 4.10330469, 4.23153296, 4.35976123,
       4.48798951, 4.61621778, 4.74444605, 4.87267432, 5.00090259,
       5.12913086, 5.25735913, 5.38558741, 5.51381568, 5.64204395,
       5.77027222, 5.89850049, 6.02672876, 6.15495704, 6.28318531])

In [70]:
%%timeit #mide el tiempo de ejecucion de la celda
y = np.sin(x)
y

1.5 µs ± 377 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [71]:
%%timeit #mide el tiempo de ejecucion de la celda
y2 = np.zeros(50)
for i in range(50):
    y2[i] = np.sin(x[i])
y2

56.8 µs ± 1.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


##  Variables aleatorias

In [78]:
b = np.random.random((5, 5))
b

array([[0.19278372, 0.77958664, 0.40257513, 0.390292  , 0.14940961],
       [0.05426478, 0.63954119, 0.26238299, 0.42010509, 0.51484944],
       [0.29252828, 0.28724166, 0.08623235, 0.52673287, 0.8203423 ],
       [0.14553078, 0.75276382, 0.20422942, 0.41377042, 0.29100204],
       [0.51837412, 0.85915279, 0.1013117 , 0.04689554, 0.72882823]])

## Unos, ceros

In [79]:
np.zeros([10, 10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
# Copiando la forma de x
np.ones_like(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Desde archivos

In [83]:
data = np.loadtxt("data/data.csv", delimiter=',', skiprows=1)
data

FileNotFoundError: data/data.csv not found.

***
# Impresión de arreglos

Cuando imprimes una matriz, NumPy la muestra de forma similar a las listas anidadas, pero con el siguiente diseño:

- el último eje se imprime de izquierda a derecha,

- el penúltimo se imprime de arriba a abajo,

- el resto también se imprime de arriba a abajo, con cada corte separado del siguiente por una línea vacía.

Las matrices unidimensionales se imprimen como filas, bidimensionales como matrices y tridimensionales como listas de matrices.

In [84]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [85]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [86]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [87]:
# Si es muy grande, se suprime parte de la salida
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [88]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


***
# Operaciones básicas

Las operaciones básicas son aplicadas elemento a elemento (*elementwise*). Se crea un nuevo arreglo lleno con el resultado

In [89]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [90]:
c = a - b
c

array([20, 29, 38, 47])

`*` opera en sentido elemento a elemento sobre los arreglos.

In [93]:
# Constante por arreglo
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [94]:
a*b

array([  0,  30,  80, 150])

In [95]:
# Arreglos lógicos
a < 35

array([ True,  True, False, False])

In [ ]:
# Arreglos lógicos
a < 35

La multiplicación matricial puede hacerse utilizando `@` o el método `dot`

In [96]:
A = np.array( [[1, 1], [0, 1]] )
B = np.array( [[2, 0], [3, 4]] )

In [97]:
A * B

array([[2, 0],
       [0, 4]])

In [98]:
A @ B #multiplicacion matricial

array([[5, 4],
       [3, 4]])

In [99]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [100]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [101]:
b = np.random.random((2,3))
b

array([[0.78014564, 0.39431684, 0.80385191],
       [0.14107316, 0.84519429, 0.0736469 ]])

Operadores `+=` y `*=` son válidos para modificar arreglos existentes.

In [102]:
a = np.ones((2,3), dtype=int)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [103]:
b = np.random.random((2,3))
b +=a
b

array([[3.27957428, 3.91301269, 3.79407864],
       [3.03468756, 3.12264209, 3.58062703]])

## Métodos útiles

In [104]:
a = np.random.random((2, 3))
a

array([[0.03702847, 0.32575376, 0.48008424],
       [0.61769299, 0.05727865, 0.30126639]])

In [106]:
a.sum() # equivalente a np.sum(a)

np.float64(1.8191044926120123)

In [105]:
a.min()

np.float64(0.037028471043811684)

In [107]:
a.max()

np.float64(0.6176929920680918)

Por defecto operan sobre el arreglo como si fueran una lista de números. Es posible especificar el eje sobre el cuál se desea aplicar la operación con el parámetro `axis`

In [108]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
# Suma de las columnas
b.sum(axis=0)

array([12, 15, 18, 21])

In [117]:
# Mínimo de cada fila
b.min(axis=1)

array([0, 4, 8])

In [119]:
#vector fila suma las columnas
b.sum(axis=0)[None,:]

array([[12, 15, 18, 21]])

In [115]:
#vector fila
b.min(axis=1)[:,np.newaxis].shape

(3, 1)

In [118]:
# Suma acumulada en las columnas
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

***
## Funciones universales (*ufuncs*)

In [129]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [121]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [122]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

Podemos definir funciones de usuario que sean universales: $$ f(x) = 2x + e^x - \sqrt{x} $$

In [123]:
def f(x):
    return 2*x + np.exp(x) - np.sqrt(x)

In [125]:
f(2)

np.float64(9.974842536557555)

In [128]:
f(a)

array([ 1.        ,  3.71828183,  9.97484254, 24.35348612, 60.59815003])

***
## Indexing, Slicing and Iterating

Los arreglos unidimensionales se pueden indexar, dividir e iterar, al igual que las listas y otras secuencias de Python.

In [140]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [133]:
a.size

10

In [134]:
a[2]

np.int64(8)

In [135]:
a[2:5]

array([ 8, 27, 64])

In [136]:
# Asignación múltiple
a[0:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [150]:
for i in range(0,6,2):
  a[i]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [151]:
def f(x,y):
    return 10*x + y

In [152]:
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [153]:
b[2, 3]

np.int64(23)

In [154]:
b[2, :]

array([20, 21, 22, 23])

In [155]:
b[:, 2]

array([ 2, 12, 22, 32, 42])

In [162]:
b[:, 2]

array([ 2, 12, 22, 32, 42])

In [161]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [163]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

Cuando se proporcionan menos índices que el número de ejes, los índices faltantes se consideran segmentos completos `:`

In [173]:
# Ultima fila, todas las columnas, toma la ultima dimension
b[-3]

array([20, 21, 22, 23])

In [185]:
c=np.ones((10,3,3))

La iteración sobre arreglos multidimensionales se realiza con respecto al primer eje

In [188]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [186]:
for row in c:
    print(row)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Sin embargo, si se desea realizar una operación en cada elemento de la matriz, se puede usar el atributo `flat` que es un iterador sobre todos los elementos de la matriz:

In [190]:
c

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [191]:
for element in c.flat:
    print(element)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [192]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [194]:
c.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [193]:
b.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

***
## Manipulación del `shape` (forma) del arreglo

Una matriz tiene una forma dada por el número de elementos a lo largo de cada eje:

In [196]:
a = np.floor ( 10 * np.random.random (( 3 , 4 )))
a

array([[3., 5., 6., 7.],
       [9., 8., 3., 4.],
       [0., 5., 7., 6.]])

In [197]:
a.shape

(3, 4)

La forma de una matriz se puede cambiar con varios comandos. Tenga en cuenta que los siguientes tres comandos devuelven una matriz modificada, pero **no cambian la matriz original**:

In [198]:
a.ravel()  # returns the array, flattened

array([3., 5., 6., 7., 9., 8., 3., 4., 0., 5., 7., 6.])

In [199]:
a.flatten()

array([3., 5., 6., 7., 9., 8., 3., 4., 0., 5., 7., 6.])

In [204]:
a.reshape(6,2)  # returns the array with a modified shape

array([[3., 5.],
       [6., 7.],
       [9., 8.],
       [3., 4.],
       [0., 5.],
       [7., 6.]])

In [205]:
a.T #traspuesto del vector

array([[3., 9., 0.],
       [5., 8., 5.],
       [6., 3., 7.],
       [7., 4., 6.]])

In [206]:
a.T.shape

(4, 3)

In [208]:
d= np.ones([3,2,1])
d.reshape(2,3)
d.T

array([[[1., 1., 1.],
        [1., 1., 1.]]])

- El orden de los elementos en la matriz resultante de `ravel()` es normalmente "estilo `C`", es decir, el índice de la derecha "cambia más rápido", por lo que el elemento después de un `[0,0]` es un `[0,1]`.

- Si la matriz se reforma a otra forma, nuevamente la matriz se trata como "estilo `C`". NumPy normalmente crea matrices almacenadas en este orden, por lo que `ravel()` generalmente no necesitará copiar su argumento, pero si la matriz se hizo tomando segmentos de otra matriz o se creó con opciones inusuales, es posible que deba copiarse.

- Las funciones `ravel()` y `reshape()` también se pueden instruir, utilizando un argumento opcional, para usar matrices de estilo FORTRAN, en las que el índice más a la izquierda cambia más rápido.

La función de `reshape` devuelve su argumento con una forma modificada, mientras que el método `ndarray.resize` modifica la matriz en sí:

In [209]:
a

array([[3., 5., 6., 7.],
       [9., 8., 3., 4.],
       [0., 5., 7., 6.]])

In [214]:
a.resize((2, 6))
a

array([[3., 5., 6., 7., 9., 8.],
       [3., 4., 0., 5., 7., 6.]])

***
## Concatenación de arreglos
Se pueden apilar varios arreglos a lo largo de diferentes ejes:

In [220]:
a = np.floor(10*np.random.random((2,2)))
a

array([[0., 3.],
       [1., 1.]])

In [216]:
b = np.floor(10*np.random.random((2,2)))
b

array([[7., 1.],
       [5., 0.]])

In [217]:
# np.vstack pide una tupla de ndarrays
np.vstack((a,b))

array([[8., 3.],
       [1., 4.],
       [7., 1.],
       [5., 0.]])

In [218]:
# np.hstack pide una tupla de ndarrays
np.hstack((a,b))

array([[8., 3., 7., 1.],
       [1., 4., 5., 0.]])

In [221]:
np.column_stack((a,b)) # Equivalente a np.hstack para arreglos 2D

array([[0., 3., 7., 1.],
       [1., 1., 5., 0.]])

In [222]:
np.hstack((a,b))

array([[0., 3., 7., 1.],
       [1., 1., 5., 0.]])

- Cuando los arreglos son 1D, `np.column_stack()` y `np.hstack()` se comportan diferente

In [223]:
a = np.array([4.,2.])
b = np.array([3.,8.])

In [224]:
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [225]:
np.hstack((a,b))

array([4., 2., 3., 8.])

- Podemos crear nuevas dimensiones en el arreglo con `np.newaxis` o con `None`

In [226]:
a[:, np.newaxis]

array([[4.],
       [2.]])

In [227]:
a[:, None]

array([[4.],
       [2.]])

In [228]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[4., 3.],
       [2., 8.]])

- Por otro lado, la función `row_stack` es equivalente a `vstack` para cualquier arreglo de entrada. De hecho, `row_stack` es un alias para `vstack`

In [ ]:
np.row_stack is np.vstack

- En general, para arreglos con más de dos dimensiones:
    
    - `hstack` apila a lo largo del segundo eje,
    
    - `vstack` apila a lo largo del primer eje y
    
    - `concatenate` permite argumentos opcionales que dan el número del eje (`axis`) a lo largo del cual debe ocurrir la concatenación.

***
## Separar un arreglo en varios más pequeños

In [ ]:
a = np.floor(10*np.random.random((2,12)))
a

In [ ]:
np.hsplit(a,3)   # Split a into 3

In [ ]:
np.hsplit(a, (3,4))   # Split a after the third and the fourth column

In [ ]:
help(np.hsplit)

***
# Mutabilidad y clonado

Al operar y manipular arreglos, los datos a veces se copian en un nuevo arreglo y otras no. Esto es a menudo una fuente de confusión para los principiantes.

Hay tres casos:

In [230]:
a = np.arange( 12 )
b = a
b is a

True

In [231]:
b.shape = 3, 4
a.shape

(3, 4)

1. Cortar una matriz devuelve una vista de ella:

In [232]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [233]:
s = a[:, 1:3]  #slices genera copias de una parte de la original
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [234]:
s is a

False

## Copia profunda

El método de copy hace una copia completa de la matriz y sus datos.

In [235]:
# a new array object with new data is created
d = a.copy()
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [236]:
d is a

False

In [237]:
d == a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [238]:
np.all(d == a)

np.True_

***
# Rutinas de NumPy

[Rutinas y funcionalidad](https://numpy.org/devdocs/reference/routines.html#routines)

***
# Para usuarios ***pro*** (como ustedes)

## *Broadcasting* (difusión)

- Este mecanismo permite que las funciones universales manejen de manera significativa entradas que no tienen exactamente la misma forma.

[General Broadcasting Rules](https://numpy.org/devdocs/user/basics.broadcasting.html)

- Un ejemplo:

In [ ]:
x = np.arange(4)
x

In [ ]:
xx = x.reshape(4,1)
xx

In [ ]:
x + xx

In [ ]:
x.shape

In [ ]:
xx.shape

- El *broadcasting* proporciona una forma conveniente de tomar el producto externo (o cualquier otra operación externa) de dos matrices. El siguiente ejemplo muestra una operación de adición externa de dos matrices 1D:

In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

In [ ]:
a[:, None] + b

Aquí, `None` inserta un nuevo eje en `a`, haciéndolo un arreglo bidimensional de `4x1`. Al combinar este arreglo de `4x1` con `b`, que tiene forma `(3,)`, resulta un arreglo de `4x3`

### ¿Por qué funciona?

- Cuando se operan dos arreglos, NumPy compara sus formas (`shape`) elemento a elemento, empezando por la última dimensión y hacia arriba.

- Dos dimensiones son compatibles cuando:
    
    - Son iguales, o
    
    - Una de ellas es 1
    
- Cuando alguna de las dos dimensiones es uno, **se utiliza la otra**.

    - En otras palabras, las dimensiones con tamaño 1 son "estiradas" o "copiadas" para ajustarse a la otra.

***
## *Fancy indexing* y trucos de indexación

- NumPy ofrece más funciones de indexación que las secuencias regulares de Python. Además de la indexación por enteros y sectores, como vimos antes, las matrices se pueden indexar por matrices de enteros y matrices de booleanos.

In [ ]:
a = np.arange(11)**2
a

In [ ]:
i = np.array( [ 1,1,3,8,5 ] )
i

In [ ]:
a[i]   # the elements of a at the positions i

In [ ]:
j = np.array([[ 3, 4], [ 9, 7 ]])  # a bidimensional array of indices
j

In [ ]:
a[j] # the same shape as j

- También podemos dar índices para más de una dimensión. Las matrices de índices para cada dimensión deben tener la misma forma.

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
i = np.array([[0,1], [1,2]])
j = np.array([[2,1], [3,3]])

In [ ]:
i

In [ ]:
j

In [ ]:
a[i,j] # i and j must have equal shape

In [ ]:
a[i,2]

In [ ]:
a[:,j]

***
### Búsqueda del máximo

In [ ]:
data = np.sin(np.arange(20)).reshape(5,4)
data

In [ ]:
# index of the maxima for each series
ind = data.argmax(axis=0)
ind

***
###  Asignación múltiple con indexación

In [ ]:
a = np.arange(5)
a

In [ ]:
a[[1,3,4]] = 0
a

In [ ]:
# Se queda la última asignación
a = np.arange(5)
a[[0,0,2]] = [1,2,3]
a

***
### Indexado con arreglos booleanos

- Cuando indexamos arreglos con otros arreglos de índices (enteros), proporcionamos la lista de índices para elegir. Con los índices booleanos, el enfoque es diferente; **elegimos explícitamente qué elementos de la matriz queremos y cuáles no**.

La forma más natural en la que uno puede pensar para la indexación booleana es usar matrices booleanas que tengan la misma forma que la matriz original:

In [ ]:
a = np.arange(12).reshape(3,4)
a

In [ ]:
b = a > 4
b

In [ ]:
a[b]

- También se puede utilizar en asignaciones:

In [ ]:
a[b] = 0
a

***
# Álgebra lineal

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

In [ ]:
a.transpose()

In [ ]:
np.linalg.inv(a)

In [ ]:
np.eye(2)

In [ ]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

j @ j

In [ ]:
y = np.array([[5.], [7.]])
y

In [ ]:
np.linalg.solve(a, y)

In [ ]:
# eigenvalores y eigenvectores
np.linalg.eig(a)

***
# Ejercicios propuestos

1. De las siguientes secciones, revisa las funciones de NumPy disponibles para darte una idea de lo que es posible hacer.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimate` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$.

    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$.

    - Estos parámetros deben ser devueltos como un arreglo de NumPy.

    - Utilice la función de lectura de archivos de NumPy.